language: node_js

node_js:
  - "12"

before_script:
  - npm install
  - npm run build

script:
- npm run test

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_KEY
  on:
    branch: master
  skip_cleanup: true